### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by alxhghs** [mrklees/CYPY#4]
Hi Alex!

Great meeting you during the conference in Boston. Do you use a virtual environment for this project? If so, do you have a requirements.txt file? I'm interested in playing around with this and also seeing if there's anything I could build based off of some of the code you've already made. 

-Alex

**Comment by mrklees** [comment]
Alex! 

So sorry for not getting back to you sooner.  I use Conda for my package management and so I should be able to provide an environment.yml which shares what packages I'm using.  Still haven't found a moment to do this though.  However, in the readme I did try to describe the packages you would need which are primarily selenium, seleniumrequests, and the Python for Windows extension which you'll need to install separately from Python.  Let me know if you have any other questions!

-A

**Comment by alxhghs** [comment]
Hi Alex,

I just thought of you because I got an update that you pushed some new changes to the cy-automation-library. Pretty cool! Are there any pieces you are currently working on that you might want additional help with? Not sure if I would be in a position to help out as an IM, but I’m definitely interested if there are. One question I would have is how hard it would be to get this code working on Mac/Linux since you use a Python for Windows extension. Is that extension just for being able to work with Microsoft Office, or is it specifically for working with Windows OS?

- Alex



Alexander Fenwood Hughes
Impact Manager
He, Him, His



City Year Boston
Boston, MA
C: 971.701.0763
ahughes1@cityyear.org<mailto:ahughes1@cityyear.org>  |  www.cityyear.org<http://www.cityyear.org>

Blog<https://www.cityyear.org/boston/blog><https://www.cityyear.org/blog> | Snapchat<https://www.snapchat.com/add/cityyear> <https://www.snapchat.com/add/cityyear> | Instagram<https://www.instagram.com/cityyearboston/><https://www.instagram.com/cityyear/> | Facebook<https://www.facebook.com/cityyear/><https://www.facebook.com/cityyear/> | Twitter<https://twitter.com/cityyearboston><https://twitter.com/cityyear> | YouTube<https://www.youtube.com/user/cityyear><https://www.youtube.com/user/cityyear> | Apply<https://www.cityyear.org/join-the-corps/how-to-apply><https://www.cityyear.org/join-the-corps/how-to-apply>
#makebetterhappen





On Nov 14, 2017, at 4:52 PM, Alex Perusse <notifications@github.com<mailto:notifications@github.com>> wrote:


Alex!

So sorry for not getting back to you sooner. I use Conda for my package management and so I should be able to provide an environment.yml which shares what packages I'm using. Still haven't found a moment to do this though. However, in the readme I did try to describe the packages you would need which are primarily selenium, seleniumrequests, and the Python for Windows extension which you'll need to install separately from Python. Let me know if you have any other questions!

-A

**Comment by mrklees** [comment]
Alex! You know, I'm fairly certain that this particular application for Excel won't work with OS X.  Primarily this is because the object of the script is to refresh the queries in the workbook, and currently the OS X version of excel doesn't support those queries.  However, for different use cases like updating there are packages like xlwings which essentially allows you to create and manipulate excel workbooks at will.

In your situation, I suspect a slightly more useful case are scripts I've made for automating actions in cyschoolhouse.  The stuff I've written has mostly focused on some start of year setup tasks, but if you take a look at some of the CHI ipynb you can see examples of using selenium to pull reports from cyschoolhouse automatically.  This could be useful if there are any reports you pull regularly from cyschoolhouse to track your team!
